# Generated by Django 4.1.2 on 2023-04-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='faculte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_fac', models.IntegerField()),
                ('nom_fac', models.CharField(max_length=50)),
                ('id_univ', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='université',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_univ', models.IntegerField()),
                ('nom_univ', models.CharField(max_length=50)),
            ],
        ),
    ]
