# Generated by Django 4.1.2 on 2023-04-14 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculte',
            name='id_univ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.université'),
        ),
    ]
